import { query, mutation } from "./_generated/server";
import { v } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";

export const createInvoice = mutation({
  args: {
    patientId: v.id("patients"),
    amount: v.number(),
    currency: v.optional(v.union(v.literal("BRL"), v.literal("EUR"))),
    description: v.string(),
    paymentDate: v.string(),
    appointmentIds: v.optional(v.array(v.id("appointments"))),
    sessionDetails: v.optional(v.string()),
    paymentMethod: v.optional(v.union(
      v.literal("pix"),
      v.literal("cartao_credito"),
      v.literal("mbway"),
      v.literal("paypal"),
      v.literal("stripe"),
      v.literal("wise"),
      v.literal("revolut"),
      v.literal("manual")
    )),
    isAutoGenerated: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new Error("Não autorizado");
    }

    const patient = await ctx.db.get(args.patientId);
    if (!patient) {
      throw new Error("Paciente não encontrado");
    }

    // Generate invoice number
    const invoiceNumber = `INV-${Date.now()}`;

    const invoiceId = await ctx.db.insert("invoices", {
      patientId: args.patientId,
      therapistId: userId,
      amount: args.amount,
      currency: args.currency || "BRL",
      description: args.description,
      status: "pending",
      paymentDate: args.paymentDate,
      appointmentIds: args.appointmentIds,
      sessionDetails: args.sessionDetails,
      paymentMethod: args.paymentMethod,
      createdAt: Date.now(),
    });

    return { invoiceId, invoiceNumber };
  },
});

export const deleteInvoice = mutation({
  args: {
    invoiceId: v.id("invoices"),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new Error("Não autorizado");
    }

    const invoice = await ctx.db.get(args.invoiceId);
    if (!invoice || invoice.therapistId !== userId) {
      throw new Error("Cobrança não encontrada");
    }

    await ctx.db.delete(args.invoiceId);
    return args.invoiceId;
  },
});

export const generateInvoiceHTML = mutation({
  args: {
    invoiceId: v.id("invoices"),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new Error("Não autorizado");
    }

    const invoice = await ctx.db.get(args.invoiceId);
    if (!invoice || invoice.therapistId !== userId) {
      throw new Error("Fatura não encontrada");
    }

    const patient = await ctx.db.get(invoice.patientId);
    if (!patient) {
      throw new Error("Paciente não encontrado");
    }

    // Get therapist profile
    const therapistProfile = await ctx.db
      .query("therapistProfiles")
      .withIndex("by_therapist", (q) => q.eq("therapistId", userId))
      .first();

    // Get sessions details if available
    let sessionsDetails: any[] = [];
    if (invoice.appointmentIds && invoice.appointmentIds.length > 0) {
      const sessionPromises = await Promise.all(
        invoice.appointmentIds.map(async (appointmentId) => {
          const appointment = await ctx.db.get(appointmentId);
          if (appointment) {
            return {
              date: appointment.date,
              time: appointment.time,
              duration: appointment.duration || 60,
              treatmentType: appointment.treatmentType,
              sessionType: appointment.sessionType,
            };
          }
          return null;
        })
      );
      sessionsDetails = sessionPromises.filter(Boolean);
    }

    const invoiceData = {
      invoiceNumber: `INV-${invoice._id}`,
      issueDate: new Date(invoice.createdAt).toISOString().split('T')[0],
      dueDate: invoice.paymentDate,
      patient: {
        name: patient.fullName,
        email: patient.email,
        phone: patient.phone,
        address: patient.address,
      },
      therapist: {
        name: therapistProfile?.fullName || "Débora Pastori",
        profession: therapistProfile?.profession || "Psicóloga",
        crp: therapistProfile?.crpNumber || "[Número do CRP]",
        email: therapistProfile?.email || "",
        phone: therapistProfile?.phone || "",
        address: therapistProfile?.address || "",
        logoUrl: therapistProfile?.logoStorageId ? await ctx.storage.getUrl(therapistProfile.logoStorageId) : null,
      },
      invoice: {
        id: invoice._id,
        description: invoice.description,
        amount: invoice.amount,
        currency: invoice.currency,
        status: invoice.status,
        paymentMethod: invoice.paymentMethod,
      },
      sessions: sessionsDetails,
      totalHours: sessionsDetails.reduce((total, session) => total + (session?.duration || 60), 0) / 60,
      sessionDetails: invoice.sessionDetails,
    };

    const html = generateInvoiceHTMLTemplate(invoiceData);
    
    return {
      html,
      invoiceNumber: invoiceData.invoiceNumber,
      filename: `cobranca-${invoiceData.invoiceNumber}.html`,
      invoiceData,
    };
  },
});

export const markInvoiceAsPaid = mutation({
  args: {
    invoiceId: v.id("invoices"),
    paymentMethod: v.optional(v.union(
      v.literal("pix"),
      v.literal("cartao_credito"),
      v.literal("mbway"),
      v.literal("paypal"),
      v.literal("stripe"),
      v.literal("wise"),
      v.literal("revolut"),
      v.literal("manual")
    )),
    paidAt: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new Error("Não autorizado");
    }

    const invoice = await ctx.db.get(args.invoiceId);
    if (!invoice || invoice.therapistId !== userId) {
      throw new Error("Fatura não encontrada");
    }

    await ctx.db.patch(args.invoiceId, {
      status: "paid",
      paymentMethod: args.paymentMethod,
      paidAt: args.paidAt || Date.now(),
    });

    return args.invoiceId;
  },
});

export const getInvoicesByTherapist = query({
  args: { 
    status: v.optional(v.union(
      v.literal("pending"),
      v.literal("paid"),
      v.literal("cancelled"),
      v.literal("overdue")
    ))
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      return [];
    }

    let invoices = await ctx.db
      .query("invoices")
      .withIndex("by_therapist", (q) => q.eq("therapistId", userId))
      .order("desc")
      .collect();

    if (args.status) {
      invoices = invoices.filter(invoice => invoice.status === args.status);
    }

    const invoicesWithDetails = await Promise.all(
      invoices.map(async (invoice) => {
        const patient = await ctx.db.get(invoice.patientId);
        return {
          ...invoice,
          patient,
        };
      })
    );

    return invoicesWithDetails;
  },
});

export const getInvoicesByPatient = query({
  args: { patientId: v.id("patients") },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      return [];
    }

    const invoices = await ctx.db
      .query("invoices")
      .withIndex("by_patient", (q) => q.eq("patientId", args.patientId))
      .order("desc")
      .collect();

    return invoices.filter(invoice => invoice.therapistId === userId);
  },
});

export const calculateInvoiceAmount = mutation({
  args: {
    patientId: v.id("patients"),
    appointmentIds: v.array(v.id("appointments")),
    currency: v.union(v.literal("BRL"), v.literal("EUR")),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new Error("Não autorizado");
    }

    const patient = await ctx.db.get(args.patientId);
    if (!patient) {
      throw new Error("Paciente não encontrado");
    }

    // Get payment settings
    const settings = await ctx.db
      .query("paymentSettings")
      .withIndex("by_therapist", (q) => q.eq("therapistId", userId))
      .first();

    const hourlyRate = args.currency === "BRL" 
      ? (settings?.sessionPriceBRL || patient.sessionPrice || 150)
      : (settings?.sessionPriceEUR || 80);

    // Get appointments and calculate total
    const appointments = await Promise.all(
      args.appointmentIds.map(id => ctx.db.get(id))
    );

    let totalMinutes = 0;
    let sessionDetails = [];

    for (const appointment of appointments) {
      if (appointment && appointment.status === "completed") {
        const duration = appointment.duration || 60;
        totalMinutes += duration;
        
        sessionDetails.push({
          date: appointment.date,
          time: appointment.time,
          duration,
          treatmentType: appointment.treatmentType,
          sessionType: appointment.sessionType,
        });
      }
    }

    const totalHours = totalMinutes / 60;
    const totalAmount = totalHours * hourlyRate;

    const sessionDetailsText = sessionDetails
      .map(s => `${new Date(s.date + 'T00:00:00').toLocaleDateString('pt-BR')} às ${s.time} - ${s.duration}min (${s.treatmentType} - ${s.sessionType})`)
      .join('\n');

    return {
      totalHours,
      totalMinutes,
      hourlyRate,
      totalAmount,
      sessionDetails: sessionDetailsText,
      sessionsCount: sessionDetails.length,
    };
  },
});

function generateInvoiceHTMLTemplate(invoiceData: any): string {
  const currencySymbol = invoiceData.invoice.currency === 'EUR' ? '€' : 'R$';
  const logoSection = invoiceData.therapist.logoUrl 
    ? `<img src="${invoiceData.therapist.logoUrl}" alt="Logo" style="max-height: 80px; margin-bottom: 10px;">`
    : '';
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Cobrança - ${invoiceData.invoiceNumber}</title>
      <style>
        body { 
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
          max-width: 800px; 
          margin: 0 auto; 
          padding: 20px; 
          line-height: 1.6;
          color: #333;
        }
        .header { 
          text-align: center; 
          border-bottom: 3px solid #2563eb; 
          padding-bottom: 20px; 
          margin-bottom: 30px;
          background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
          padding: 30px;
          border-radius: 10px;
        }
        .header h1 {
          color: #2563eb;
          margin: 10px 0;
          font-size: 28px;
        }
        .header h2 {
          color: #475569;
          margin: 5px 0;
          font-weight: 400;
        }
        .invoice-info { 
          display: flex; 
          justify-content: space-between; 
          margin-bottom: 30px;
          gap: 30px;
        }
        .info-section {
          flex: 1;
          background: #f8fafc;
          padding: 20px;
          border-radius: 8px;
          border-left: 4px solid #2563eb;
        }
        .info-section h3 { 
          color: #2563eb; 
          margin-top: 0;
          margin-bottom: 15px;
          font-size: 16px;
        }
        .info-section p {
          margin: 8px 0;
          font-size: 14px;
        }
        .section { 
          margin-bottom: 30px;
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          overflow: hidden;
        }
        .section-header {
          background: #2563eb;
          color: white;
          padding: 15px 20px;
          margin: 0;
          font-size: 16px;
          font-weight: 600;
        }
        .section-content {
          padding: 20px;
        }
        .sessions-table { 
          width: 100%; 
          border-collapse: collapse; 
          margin-top: 15px;
          font-size: 14px;
        }
        .sessions-table th, .sessions-table td { 
          border: 1px solid #e2e8f0; 
          padding: 12px 8px; 
          text-align: left; 
        }
        .sessions-table th { 
          background-color: #f1f5f9; 
          font-weight: 600;
          color: #475569;
        }
        .sessions-table tr:nth-child(even) {
          background-color: #f8fafc;
        }
        .amount-section {
          background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%);
          color: white;
          padding: 25px;
          border-radius: 10px;
          text-align: center;
          margin: 30px 0;
        }
        .amount-section h3 {
          margin: 0 0 10px 0;
          font-size: 18px;
        }
        .amount-section .amount {
          font-size: 32px;
          font-weight: bold;
          margin: 10px 0;
        }
        .payment-info {
          background: #fef3c7;
          border: 1px solid #f59e0b;
          border-radius: 8px;
          padding: 20px;
          margin: 20px 0;
        }
        .payment-info h4 {
          color: #92400e;
          margin-top: 0;
        }
        .footer { 
          margin-top: 40px; 
          text-align: center; 
          font-size: 12px; 
          color: #64748b;
          border-top: 1px solid #e2e8f0;
          padding-top: 20px;
        }
        .status-badge {
          display: inline-block;
          padding: 4px 12px;
          border-radius: 20px;
          font-size: 12px;
          font-weight: 600;
          text-transform: uppercase;
        }
        .status-pending {
          background: #fef3c7;
          color: #92400e;
        }
        .status-paid {
          background: #d1fae5;
          color: #065f46;
        }
        .qr-code-section {
          text-align: center;
          margin: 20px 0;
          padding: 20px;
          background: #f8fafc;
          border-radius: 8px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        ${logoSection}
        <h1>COBRANÇA DE SERVIÇOS</h1>
        <h2>${invoiceData.therapist.name}</h2>
        <p>${invoiceData.therapist.profession} - CRP: ${invoiceData.therapist.crp}</p>
        <p style="margin-top: 15px;"><strong>Cobrança Nº:</strong> ${invoiceData.invoiceNumber}</p>
        <span class="status-badge status-${invoiceData.invoice.status}">
          ${invoiceData.invoice.status === 'pending' ? 'Pendente' : 
            invoiceData.invoice.status === 'paid' ? 'Pago' : 
            invoiceData.invoice.status === 'overdue' ? 'Vencido' : 'Cancelado'}
        </span>
      </div>

      <div class="invoice-info">
        <div class="info-section">
          <h3>📋 Dados do Paciente</h3>
          <p><strong>Nome:</strong> ${invoiceData.patient.name}</p>
          <p><strong>E-mail:</strong> ${invoiceData.patient.email}</p>
          <p><strong>Telefone:</strong> ${invoiceData.patient.phone}</p>
          ${invoiceData.patient.address ? `<p><strong>Endereço:</strong> ${invoiceData.patient.address}</p>` : ''}
        </div>
        <div class="info-section">
          <h3>📅 Informações da Cobrança</h3>
          <p><strong>Data de Emissão:</strong> ${new Date(invoiceData.issueDate + 'T00:00:00').toLocaleDateString('pt-BR')}</p>
          <p><strong>Vencimento:</strong> ${new Date(invoiceData.dueDate + 'T00:00:00').toLocaleDateString('pt-BR')}</p>
          <p><strong>Sessões:</strong> ${invoiceData.sessions.length} sessão${invoiceData.sessions.length !== 1 ? 'ões' : ''}</p>
          <p><strong>Total de Horas:</strong> ${invoiceData.totalHours.toFixed(2)}h</p>
        </div>
      </div>

      <div class="section">
        <h3 class="section-header">💼 Descrição dos Serviços</h3>
        <div class="section-content">
          <p><strong>Serviço:</strong> ${invoiceData.invoice.description}</p>
          
          ${invoiceData.sessions.length > 0 ? `
            <table class="sessions-table">
              <thead>
                <tr>
                  <th>📅 Data</th>
                  <th>🕐 Horário</th>
                  <th>⏱️ Duração</th>
                  <th>🎯 Tipo</th>
                  <th>💻 Modalidade</th>
                </tr>
              </thead>
              <tbody>
                ${invoiceData.sessions.map((session: any) => `
                  <tr>
                    <td>${new Date(session.date + 'T00:00:00').toLocaleDateString('pt-BR')}</td>
                    <td>${session.time}</td>
                    <td>${session.duration} min</td>
                    <td>${session.treatmentType}</td>
                    <td>${session.sessionType}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          ` : ''}
          
          ${invoiceData.sessionDetails ? `<p style="margin-top: 15px;"><strong>Detalhes Adicionais:</strong><br>${invoiceData.sessionDetails.replace(/\n/g, '<br>')}</p>` : ''}
        </div>
      </div>

      <div class="amount-section">
        <h3>💰 Valor Total a Pagar</h3>
        <div class="amount">${currencySymbol} ${invoiceData.invoice.amount.toFixed(2).replace('.', ',')}</div>
        <p>Valor referente a ${invoiceData.sessions.length} sessão${invoiceData.sessions.length !== 1 ? 'ões' : ''} de ${invoiceData.therapist.profession.toLowerCase()}</p>
      </div>

      ${invoiceData.invoice.status === 'pending' ? `
        <div class="payment-info">
          <h4>💳 Informações para Pagamento</h4>
          <p><strong>Vencimento:</strong> ${new Date(invoiceData.dueDate + 'T00:00:00').toLocaleDateString('pt-BR')}</p>
          <p><strong>Formas de Pagamento Aceitas:</strong></p>
          <ul>
            <li>PIX (Chave: ${invoiceData.therapist.email || '[Chave PIX]'})</li>
            <li>Transferência Bancária</li>
            <li>MBWay (Portugal)</li>
            <li>PayPal</li>
          </ul>
          <p><em>Após o pagamento, envie o comprovante para confirmação.</em></p>
        </div>
      ` : ''}

      <div class="section">
        <h3 class="section-header">👩‍⚕️ Dados do Profissional</h3>
        <div class="section-content">
          <p><strong>Nome:</strong> ${invoiceData.therapist.name}</p>
          <p><strong>Profissão:</strong> ${invoiceData.therapist.profession}</p>
          <p><strong>CRP:</strong> ${invoiceData.therapist.crp}</p>
          ${invoiceData.therapist.email ? `<p><strong>E-mail:</strong> ${invoiceData.therapist.email}</p>` : ''}
          ${invoiceData.therapist.phone ? `<p><strong>Telefone:</strong> ${invoiceData.therapist.phone}</p>` : ''}
          ${invoiceData.therapist.address ? `<p><strong>Endereço:</strong> ${invoiceData.therapist.address}</p>` : ''}
        </div>
      </div>

      <div class="footer">
        <p>Esta cobrança refere-se aos serviços de ${invoiceData.therapist.profession.toLowerCase()} prestados conforme acordado.</p>
        <p>Em caso de dúvidas, entre em contato através dos dados acima.</p>
        <p>Documento gerado automaticamente em: ${new Date().toLocaleString('pt-BR')}</p>
      </div>
    </body>
    </html>
  `;
}

export const getPaymentSettings = query({
  args: {},
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      return null;
    }

    const settings = await ctx.db
      .query("paymentSettings")
      .withIndex("by_therapist", (q) => q.eq("therapistId", userId))
      .first();

    return settings;
  },
});

export const updateInvoiceStatus = mutation({
  args: {
    invoiceId: v.id("invoices"),
    status: v.union(
      v.literal("pending"),
      v.literal("paid"),
      v.literal("cancelled"),
      v.literal("overdue")
    ),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new Error("Não autorizado");
    }

    const invoice = await ctx.db.get(args.invoiceId);
    if (!invoice || invoice.therapistId !== userId) {
      throw new Error("Fatura não encontrada");
    }

    await ctx.db.patch(args.invoiceId, {
      status: args.status,
    });

    return args.invoiceId;
  },
});
